// Test-only fixtures; the production application has no product fallback.
const {chromium}=require('playwright'),{spawn}=require('node:child_process'),assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os');
const server=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:'8183'}}),base='http://localhost:8183',key='domorelli_cart_v1';
const fixture=[
{id:1,name:'Novo Hambúrguer',description:'Pão & carne / + "queijo" — açafrão 🍔',category:'Hambúrgueres Artesanais',price_cents:2900,image_path:'products/1/test.png',featured:true,position:2},
{id:2,name:'Porção & molho / + "açúcar" 🍟',description:null,category:'Entradas',price_cents:2550,image_path:null,featured:false,position:3},
{id:3,name:'Whisky',description:null,category:'Bebidas alcoólicas e whisky',price_cents:null,image_path:null,featured:true,position:0},
{id:4,name:'<img src=x onerror=alert(1)>',description:'<script>alert(1)</script>',category:'Entradas',price_cents:1300,image_path:null,featured:false,position:1},
{id:5,name:'Primeiro por ID',description:null,category:'Entradas',price_cents:0,image_path:null,featured:false,position:1}];
let products=structuredClone(fixture),fail=false,requests=0,delay=0;
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX9sAAAAASUVORK5CYII=','base64');
(async()=>{let browser;try{
await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);});
browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage']});
const context=await browser.newContext({reducedMotion:'reduce'});
await context.addInitScript(()=>{sessionStorage.setItem('domorelli:intro-seen','1');window.testOpened=[];window.open=url=>{testOpened.push(url);return {};};});
await context.route('**/assets/js/config.js',async route=>{const response=await route.fetch();const body=(await response.text()).replace("supabaseUrl: ''","supabaseUrl: 'https://domorelli-test.supabase.co'").replace("supabasePublishableKey: ''","supabasePublishableKey: 'sb_publishable_test_only'");await route.fulfill({response,body});});
await context.route('https://domorelli-test.supabase.co/**',async route=>{const url=new URL(route.request().url());if(url.pathname.includes('/storage/'))return route.fulfill({status:200,contentType:'image/png',body:png});assert.ok(url.pathname.includes('/rest/v1/products'));assert.equal(route.request().method(),'GET');requests++;if(delay)await new Promise(r=>setTimeout(r,delay));await route.fulfill({status:fail?503:200,contentType:'application/json',body:JSON.stringify(fail?{message:'PRIVATE INTERNAL ERROR'}:products)});});
const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const ready=()=>page.waitForFunction(()=>window.DomorelliCatalog?.getState()==='ready');
const add=id=>page.locator(`#products [data-product-id="${id}"] button[data-product-action="add"]`).click();
const open=()=>page.locator('#cart-open').click(),close=()=>page.locator('#cart-close').click();
const total=async text=>assert.equal((await page.locator('#cart-total').textContent()).replace(/\s/g,' '),text);
const storage=()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key),latest=()=>page.evaluate(()=>testOpened.at(-1));
const setStored=async value=>{await page.evaluate(([k,v])=>localStorage.setItem(k,v),[key,typeof value==='string'?value:JSON.stringify(value)]);await page.reload();await ready();};
await page.goto(base);await ready();assert.equal(requests,1);
assert.deepEqual(await page.locator('.menu__category-title').allTextContents(),['Entradas','Hambúrgueres Artesanais','Bebidas alcoólicas e whisky']);
assert.deepEqual(await page.locator('.menu__category').first().locator('.menu__item').evaluateAll(nodes=>nodes.map(n=>Number(n.dataset.productId))),[4,5,2]);
assert.equal(await page.locator('#products .menu__item').count(),5);assert.equal(await page.locator('.signature__item').count(),2);assert.equal(await page.locator('#products .product-image').count(),1);assert.equal(await page.locator('#products .menu__item-name img').count(),0);
assert.equal(await page.locator('[data-product-id="3"] [data-product-action="add"]').count(),0);
await page.locator('#products [data-product-id="3"] button').click();assert.equal(new URL(await latest()).searchParams.get('text'),'Olá! Gostaria de consultar o preço de Whisky na Domorelli Steakhouse.');assert.equal((await storage()).length,0);
await open();await page.locator('#cart-checkout').click();assert.equal(await page.evaluate(()=>testOpened.length),1);assert.match(await page.locator('#cart-status').textContent(),/Adicione pelo menos/);await close();
await add(1);await add(1);await open();await total('R$ 58,00');assert.equal(await page.locator('#cart-count').textContent(),'2');assert.deepEqual(await storage(),[{productId:1,quantity:2}]);
await page.locator('#cart-notes').fill('Sem cebola & açúcar / + "molho"\nBem passado 🍔');await page.locator('#cart-checkout').click();let url=new URL(await latest());assert.equal(url.hostname,'wa.me');assert.equal(url.pathname,'/5538991276369');assert.match(url.searchParams.get('text'),/2x Novo Hambúrguer\nR\$\s29,00 cada — R\$\s58,00/);assert.match(url.searchParams.get('text'),/Sem cebola & açúcar \/ \+ "molho"\nBem passado 🍔/);assert.equal((await storage())[0].quantity,2);
await page.locator('#cart-clear').focus();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'cart-close');await page.keyboard.press('Escape');assert.equal(await page.locator('#cart-dialog').evaluate(n=>n.open),false);assert.equal(await page.evaluate(()=>document.activeElement.id),'cart-open');
products[0].price_cents=3100;await page.reload();await ready();await open();await total('R$ 62,00');await page.locator('#cart-checkout').click();assert.match(new URL(await latest()).searchParams.get('text'),/Total: R\$\s62,00/);
await page.getByRole('button',{name:'Aumentar quantidade de Novo Hambúrguer',exact:true}).click();await total('R$ 93,00');await page.getByRole('button',{name:'Diminuir quantidade de Novo Hambúrguer',exact:true}).click();await total('R$ 62,00');
await close();await add(2);await open();await total('R$ 87,50');await page.locator('#cart-checkout').click();let message=new URL(await latest()).searchParams.get('text');assert.match(message,/1x Porção & molho \/ \+ "açúcar" 🍟/);assert.ok(!message.includes('Observações:'));
await page.getByRole('button',{name:'Remover Novo Hambúrguer',exact:true}).click();await total('R$ 25,50');await page.getByRole('button',{name:'Diminuir quantidade de Porção & molho / + "açúcar" 🍟',exact:true}).click();await total('R$ 0,00');assert.deepEqual(await storage(),[]);await close();
for(let i=0;i<3;i++){await open();await close();}await add(1);assert.equal((await storage())[0].quantity,1);await open();await page.locator('#cart-clear').click();assert.deepEqual(await storage(),[]);await close();
await setStored([{productId:1,quantity:2},{productId:999,quantity:1},{productId:3,quantity:3}]);assert.deepEqual(await storage(),[{productId:1,quantity:2}]);products[0].price_cents=null;await page.reload();await ready();assert.deepEqual(await storage(),[]);
await setStored('bad-json');assert.deepEqual(await storage(),[]);await setStored({items:[{productId:2,quantity:1}]});assert.deepEqual(await storage(),[]);
await setStored([{productId:2,quantity:0},{productId:2,quantity:-1},{productId:2,quantity:1.5},{productId:2,quantity:1000},{productId:'2',quantity:1},{productId:2,quantity:1},{productId:2,quantity:2,price:1,name:'forged'}]);assert.deepEqual(await storage(),[{productId:2,quantity:3}]);
await setStored([{productId:2,quantity:999}]);await add(2);assert.equal((await storage())[0].quantity,999);
fail=true;delay=200;await page.reload();await page.waitForFunction(()=>window.DomorelliCatalog?.getState()==='loading');assert.equal(await page.locator('#products .menu__item').count(),0);await page.waitForFunction(()=>window.DomorelliCatalog.getState()==='error');assert.ok(!(await page.locator('body').textContent()).includes('PRIVATE INTERNAL ERROR'));
await open();assert.equal(await page.locator('#cart-checkout').isDisabled(),true);assert.equal((await storage())[0].quantity,999);await close();fail=false;delay=0;products=structuredClone(fixture);await page.locator('#menu-retry').click();await ready();assert.equal(await page.locator('#products .menu__item').count(),5);
await setStored([{productId:1,quantity:2},{productId:2,quantity:1}]);
for(const width of [320,375,390,430]){await page.setViewportSize({width,height:844});await page.locator('#cardapio').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,`page overflow ${width}`);await open();await total('R$ 83,50');assert.equal(await page.locator('#cart-dialog').evaluate(n=>n.scrollWidth<=n.clientWidth),true,`dialog overflow ${width}`);await page.locator('#cart-notes').fill('Sem cebola');await page.locator('#cart-checkout').click();await page.screenshot({path:path.join(os.tmpdir(),`domorelli-p2-cart-${width}.png`)});await close();await page.locator('#products .menu__item[data-product-id="1"]').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(os.tmpdir(),`domorelli-p2-catalog-${width}.png`)});}
await page.setViewportSize({width:1440,height:1000});await page.locator('.signature').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(os.tmpdir(),'domorelli-p2-desktop.png')});
products=products.map(p=>({...p,featured:false}));await page.reload();await ready();assert.equal(await page.locator('.signature').isVisible(),false);products=[];await page.reload();await ready();assert.equal(await page.locator('#products .menu__item').count(),0);assert.deepEqual(await storage(),[]);
products=structuredClone(fixture);const blocked=await context.newPage();await blocked.addInitScript(()=>{Storage.prototype.getItem=()=>{throw new Error('blocked');};Storage.prototype.setItem=()=>{throw new Error('blocked');};});await blocked.goto(base);await blocked.waitForFunction(()=>window.DomorelliCatalog?.getState()==='ready');await blocked.locator('#products [data-product-id="1"] button').click();await blocked.locator('#cart-open').click();assert.equal(await blocked.locator('#cart-count').textContent(),'1');assert.equal(await blocked.locator('#cart-storage').isVisible(),true);
assert.deepEqual(errors,[]);console.log('PASS P2: actual SDK/intercepted HTTP; catalog order/photos/null/XSS/featured; cart operations/persistence/current prices/deleted/null/invalid and blocked storage; WhatsApp encoding; retry; mobile 320/375/390/430; keyboard. No remote writes/messages.');
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
